"""add risk feedbacks

Revision ID: 0f88958c38f3
Revises: 51017d792629
Create Date: 2026-07-23 21:46:56.406719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f88958c38f3'
down_revision: Union[str, Sequence[str], None] = '51017d792629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('expected_risk_level', sa.String(length=16), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['risk_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_risk_feedbacks_event_user')
    )
    op.create_index(op.f('ix_risk_feedbacks_event_id'), 'risk_feedbacks', ['event_id'], unique=False)
    op.create_index(op.f('ix_risk_feedbacks_user_id'), 'risk_feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_feedbacks_user_id'), table_name='risk_feedbacks')
    op.drop_index(op.f('ix_risk_feedbacks_event_id'), table_name='risk_feedbacks')
    op.drop_table('risk_feedbacks')
    # ### end Alembic commands ###
