"""add family alerts

Revision ID: 63f776569546
Revises: e10830f8cc48
Create Date: 2026-07-26 17:22:32.376523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f776569546'
down_revision: Union[str, Sequence[str], None] = 'e10830f8cc48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('risk_event_id', sa.Uuid(), nullable=False),
    sa.Column('subject_user_id', sa.Uuid(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high')", name='ck_family_alerts_risk_level'),
    sa.CheckConstraint("status IN ('pending', 'acknowledged', 'resolved', 'cancelled')", name='ck_family_alerts_status'),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'risk_event_id', name='uq_family_alerts_family_event')
    )
    op.create_index(op.f('ix_family_alerts_acknowledged_by_user_id'), 'family_alerts', ['acknowledged_by_user_id'], unique=False)
    op.create_index(op.f('ix_family_alerts_family_id'), 'family_alerts', ['family_id'], unique=False)
    op.create_index('ix_family_alerts_family_status_created', 'family_alerts', ['family_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_family_alerts_resolved_by_user_id'), 'family_alerts', ['resolved_by_user_id'], unique=False)
    op.create_index(op.f('ix_family_alerts_risk_event_id'), 'family_alerts', ['risk_event_id'], unique=False)
    op.create_index(op.f('ix_family_alerts_status'), 'family_alerts', ['status'], unique=False)
    op.create_index('ix_family_alerts_subject_created', 'family_alerts', ['subject_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_family_alerts_subject_user_id'), 'family_alerts', ['subject_user_id'], unique=False)
    op.create_table('family_alert_recipients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('trusted_contact_id', sa.Uuid(), nullable=True),
    sa.Column('linked_user_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_name', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('in_app', 'phone', 'sms', 'email')", name='ck_family_alert_recipients_channel'),
    sa.CheckConstraint("delivery_status IN ('pending', 'sent', 'failed', 'skipped')", name='ck_family_alert_recipients_delivery_status'),
    sa.ForeignKeyConstraint(['alert_id'], ['family_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trusted_contact_id'], ['trusted_contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'trusted_contact_id', 'channel', name='uq_family_alert_recipients_contact_channel')
    )
    op.create_index(op.f('ix_family_alert_recipients_alert_id'), 'family_alert_recipients', ['alert_id'], unique=False)
    op.create_index('ix_family_alert_recipients_delivery', 'family_alert_recipients', ['delivery_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_family_alert_recipients_delivery_status'), 'family_alert_recipients', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_family_alert_recipients_linked_user_id'), 'family_alert_recipients', ['linked_user_id'], unique=False)
    op.create_index(op.f('ix_family_alert_recipients_trusted_contact_id'), 'family_alert_recipients', ['trusted_contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_alert_recipients_trusted_contact_id'), table_name='family_alert_recipients')
    op.drop_index(op.f('ix_family_alert_recipients_linked_user_id'), table_name='family_alert_recipients')
    op.drop_index(op.f('ix_family_alert_recipients_delivery_status'), table_name='family_alert_recipients')
    op.drop_index('ix_family_alert_recipients_delivery', table_name='family_alert_recipients')
    op.drop_index(op.f('ix_family_alert_recipients_alert_id'), table_name='family_alert_recipients')
    op.drop_table('family_alert_recipients')
    op.drop_index(op.f('ix_family_alerts_subject_user_id'), table_name='family_alerts')
    op.drop_index('ix_family_alerts_subject_created', table_name='family_alerts')
    op.drop_index(op.f('ix_family_alerts_status'), table_name='family_alerts')
    op.drop_index(op.f('ix_family_alerts_risk_event_id'), table_name='family_alerts')
    op.drop_index(op.f('ix_family_alerts_resolved_by_user_id'), table_name='family_alerts')
    op.drop_index('ix_family_alerts_family_status_created', table_name='family_alerts')
    op.drop_index(op.f('ix_family_alerts_family_id'), table_name='family_alerts')
    op.drop_index(op.f('ix_family_alerts_acknowledged_by_user_id'), table_name='family_alerts')
    op.drop_table('family_alerts')
    # ### end Alembic commands ###
