"""add trusted contacts

Revision ID: e10830f8cc48
Revises: c164c967e4ec
Create Date: 2026-07-26 17:03:21.455456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10830f8cc48'
down_revision: Union[str, Sequence[str], None] = 'c164c967e4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('subject_user_id', sa.Uuid(), nullable=False),
    sa.Column('linked_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('relationship_label', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('preferred_channel', sa.String(length=20), server_default='phone', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='3', nullable=False),
    sa.Column('can_receive_alerts', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(preferred_channel = 'email' AND email IS NOT NULL) OR (preferred_channel IN ('phone', 'sms') AND phone IS NOT NULL)", name='ck_trusted_contacts_channel_method'),
    sa.CheckConstraint("preferred_channel IN ('phone', 'sms', 'email')", name='ck_trusted_contacts_channel'),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_trusted_contacts_status'),
    sa.CheckConstraint('phone IS NOT NULL OR email IS NOT NULL', name='ck_trusted_contacts_contact_method'),
    sa.CheckConstraint('priority BETWEEN 1 AND 5', name='ck_trusted_contacts_priority'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'subject_user_id', 'email', name='uq_trusted_contacts_subject_email'),
    sa.UniqueConstraint('family_id', 'subject_user_id', 'phone', name='uq_trusted_contacts_subject_phone')
    )
    op.create_index(op.f('ix_trusted_contacts_created_by_user_id'), 'trusted_contacts', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_trusted_contacts_family_id'), 'trusted_contacts', ['family_id'], unique=False)
    op.create_index('ix_trusted_contacts_family_subject_status', 'trusted_contacts', ['family_id', 'subject_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_trusted_contacts_linked_user_id'), 'trusted_contacts', ['linked_user_id'], unique=False)
    op.create_index(op.f('ix_trusted_contacts_status'), 'trusted_contacts', ['status'], unique=False)
    op.create_index(op.f('ix_trusted_contacts_subject_user_id'), 'trusted_contacts', ['subject_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trusted_contacts_subject_user_id'), table_name='trusted_contacts')
    op.drop_index(op.f('ix_trusted_contacts_status'), table_name='trusted_contacts')
    op.drop_index(op.f('ix_trusted_contacts_linked_user_id'), table_name='trusted_contacts')
    op.drop_index('ix_trusted_contacts_family_subject_status', table_name='trusted_contacts')
    op.drop_index(op.f('ix_trusted_contacts_family_id'), table_name='trusted_contacts')
    op.drop_index(op.f('ix_trusted_contacts_created_by_user_id'), table_name='trusted_contacts')
    op.drop_table('trusted_contacts')
    # ### end Alembic commands ###
