"""add family alert policies

Revision ID: e9c37a4df94f
Revises: 63f776569546
Create Date: 2026-07-26 19:03:14.526888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c37a4df94f'
down_revision: Union[str, Sequence[str], None] = '63f776569546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_alert_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('auto_create_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('auto_dispatch_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('minimum_risk_level', sa.String(length=20), server_default='high', nullable=False),
    sa.Column('enabled_source_types', sa.JSON(), nullable=False),
    sa.Column('max_recipients', sa.Integer(), server_default='3', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("minimum_risk_level IN ('low', 'medium', 'high')", name='ck_family_alert_policies_minimum_risk_level'),
    sa.CheckConstraint('max_recipients >= 1 AND max_recipients <= 20', name='ck_family_alert_policies_max_recipients'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_alert_policies_family_id'), 'family_alert_policies', ['family_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_alert_policies_family_id'), table_name='family_alert_policies')
    op.drop_table('family_alert_policies')
    # ### end Alembic commands ###
