"""add notification delivery attempts

Revision ID: 009dffd2bb69
Revises: 1209063597ec
Create Date: 2026-07-26 21:39:51.301824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009dffd2bb69'
down_revision: Union[str, Sequence[str], None] = '1209063597ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_alert_delivery_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('sent', 'failed', 'skipped')", name='ck_family_alert_delivery_attempts_status'),
    sa.CheckConstraint('attempt_number >= 1', name='ck_family_alert_delivery_attempts_attempt_number'),
    sa.ForeignKeyConstraint(['recipient_id'], ['family_alert_recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient_id', 'attempt_number', name='uq_family_alert_delivery_attempts_recipient_number')
    )
    op.create_index(op.f('ix_family_alert_delivery_attempts_recipient_id'), 'family_alert_delivery_attempts', ['recipient_id'], unique=False)
    op.create_index('ix_family_alert_delivery_attempts_recipient_time', 'family_alert_delivery_attempts', ['recipient_id', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_family_alert_delivery_attempts_status'), 'family_alert_delivery_attempts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_alert_delivery_attempts_status'), table_name='family_alert_delivery_attempts')
    op.drop_index('ix_family_alert_delivery_attempts_recipient_time', table_name='family_alert_delivery_attempts')
    op.drop_index(op.f('ix_family_alert_delivery_attempts_recipient_id'), table_name='family_alert_delivery_attempts')
    op.drop_table('family_alert_delivery_attempts')
    # ### end Alembic commands ###
