"""add notification delivery metadata

Revision ID: 1209063597ec
Revises: e9c37a4df94f
Create Date: 2026-07-26 21:27:34.321109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1209063597ec'
down_revision: Union[str, Sequence[str], None] = 'e9c37a4df94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_alert_recipients', sa.Column('delivery_provider', sa.String(length=64), nullable=True))
    op.add_column('family_alert_recipients', sa.Column('external_message_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_alert_recipients', 'external_message_id')
    op.drop_column('family_alert_recipients', 'delivery_provider')
    # ### end Alembic commands ###
