"""add ocr correction feedback fields

Revision ID: 6662b63aad3a
Revises: 0f88958c38f3
Create Date: 2026-07-26 01:08:49.532197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6662b63aad3a'
down_revision: Union[str, Sequence[str], None] = '0f88958c38f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_feedbacks', sa.Column('ocr_text_accurate', sa.Boolean(), nullable=True))
    op.add_column('risk_feedbacks', sa.Column('corrected_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_feedbacks', 'corrected_text')
    op.drop_column('risk_feedbacks', 'ocr_text_accurate')
    # ### end Alembic commands ###
