"""add family invitations

Revision ID: c164c967e4ec
Revises: 916c6b5332c7
Create Date: 2026-07-26 16:35:37.220267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c164c967e4ec'
down_revision: Union[str, Sequence[str], None] = '916c6b5332c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('inviter_user_id', sa.Uuid(), nullable=False),
    sa.Column('invitee_email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='member', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member')", name='ck_family_invitations_role'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'cancelled', 'expired')", name='ck_family_invitations_status'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_invitations_family_id'), 'family_invitations', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_invitations_invitee_email'), 'family_invitations', ['invitee_email'], unique=False)
    op.create_index(op.f('ix_family_invitations_inviter_user_id'), 'family_invitations', ['inviter_user_id'], unique=False)
    op.create_index('ix_family_invitations_lookup', 'family_invitations', ['family_id', 'invitee_email', 'status'], unique=False)
    op.create_index(op.f('ix_family_invitations_status'), 'family_invitations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_invitations_status'), table_name='family_invitations')
    op.drop_index('ix_family_invitations_lookup', table_name='family_invitations')
    op.drop_index(op.f('ix_family_invitations_inviter_user_id'), table_name='family_invitations')
    op.drop_index(op.f('ix_family_invitations_invitee_email'), table_name='family_invitations')
    op.drop_index(op.f('ix_family_invitations_family_id'), table_name='family_invitations')
    op.drop_table('family_invitations')
    # ### end Alembic commands ###
