"""add alert retry policy

Revision ID: c8f19c1107ad
Revises: 009dffd2bb69
Create Date: 2026-07-26 22:59:57.239363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f19c1107ad'
down_revision: Union[str, Sequence[str], None] = '009dffd2bb69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_alert_policies', sa.Column('max_retry_attempts', sa.Integer(), server_default='3', nullable=False))
    op.add_column('family_alert_policies', sa.Column('retry_cooldown_seconds', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_alert_policies', 'retry_cooldown_seconds')
    op.drop_column('family_alert_policies', 'max_retry_attempts')
    # ### end Alembic commands ###
