"""add risk event source metadata

Revision ID: dcfdb8c64b03
Revises: 6662b63aad3a
Create Date: 2026-07-26 03:12:16.654000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfdb8c64b03'
down_revision: Union[str, Sequence[str], None] = '6662b63aad3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_events', sa.Column('source_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_events', 'source_metadata')
    # ### end Alembic commands ###
